name: release
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build-windows-artifacts:
    name: build-windows-${{ matrix.platform }}
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        platform: [win32]
        include:
          - platform: win32
            arch: x64
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
        architecture: ${{ matrix.arch }}

    - name: Install poetry and dependencies
      uses: ./.github/actions/bootstrap-poetry
      with:
        os: windows
    
    - uses: git-for-windows/setup-git-for-windows-sdk@v1
      with:
        flavor: minimal
      # We install the SDK so as to have access to the msgfmt.exe binary
      # from the GNU gettext package.

    - name: "Install Windows-Mesa OpenGL DLL"
      run: |
        curl -L --output mesa.7z --url https://github.com/pal1000/mesa-dist-win/releases/download/24.2.5/mesa3d-24.2.5-release-msvc.7z
        7z x mesa.7z -o*
        powershell.exe mesa\\systemwidedeploy.cmd 1

    - name: Build release
      run: poetry run python scripts/build.py --os windows --version ${{ github.ref_name }}

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-assets-${{ matrix.platform }}
        path: ${{ github.workspace }}/dist/carveracontroller-community-*-windows-x64.exe
        retention-days: 2

  build-macos-artifacts:
    name: build-macos-${{ matrix.platform }}
    runs-on: ${{ matrix.image }}
    strategy:
      fail-fast: false
      matrix:
        platform: [ Intel, AppleSilicon ]
        include:
          - platform: Intel
            image: macos-13
          - platform: AppleSilicon
            image: macos-14
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install poetry and dependencies
      uses: ./.github/actions/bootstrap-poetry
      with:
        os: macos
    
    - name: Install create-dmg
      run: brew install create-dmg

    - name: Build release
      run: poetry run python scripts/build.py --os macos --version ${{ github.ref_name }}

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: macos-assets-${{ matrix.platform }}
        path: ${{ github.workspace }}/dist/carveracontroller-community-*.dmg
        retention-days: 2

  build-linux-artifacts:
    name: build-linux-${{ matrix.platform }}
    runs-on: ${{ matrix.image }}
    strategy:
      fail-fast: false
      matrix:
        platform: [ x64, aarch64 ]
        include:
          - platform: x64
            image: ubuntu-22.04
          - platform: aarch64
            image: ubuntu-24.04-arm
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install poetry and dependencies
      uses: ./.github/actions/bootstrap-poetry
      with:
        os: linux
    
    - name: Install MTDev
      run: sudo apt-get install -y mtdev-tools gettext

    - name: Build release
      run: xvfb-run poetry run python scripts/build.py --os linux --version ${{ github.ref_name }}

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: linux-assets-${{ matrix.platform }}
        path: ${{ github.workspace }}/dist/carveracontroller-community-*.appimage
        retention-days: 2

  build-pypi-artifacts:
    name: build-python
    runs-on: ubuntu-24.04
    permissions:
      id-token: write

    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # all history is required for the dynamic versioning plugin

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install poetry and dependencies
      uses: ./.github/actions/bootstrap-poetry
      with:
        os: linux

    - name: Build release
      run: poetry run python scripts/build.py --os pypi --version ${{ github.ref_name }}

    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1

  build-android-artifacts:
    name: build-android-armeabi-v7a
    runs-on: ${{ matrix.image }}
    strategy:
      fail-fast: false
      matrix:
        platform: [ x64 ]
        include:
          - platform: x64
            image: ubuntu-22.04
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v4

    # Used to cache dependencies with a timeout
    - name: Get Date
      id: get-date
      run: |
        echo "::set-output name=date::$(/bin/date -u "+%Y%m%d")"
      shell: bash

    - name: Cache Buildozer global directory
      uses: actions/cache@v4
      with:
        path: .buildozer_global
        key: buildozer-global-${{ hashFiles('buildozer.spec') }}

    - uses: actions/cache@v4
      with:
        path: .buildozer
        key: ${{ runner.os }}-${{ steps.get-date.outputs.date }}-${{ hashFiles('buildozer.spec') }}

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install poetry and dependencies
      uses: ./.github/actions/bootstrap-poetry
      with:
        os: linux
    
    - name: Install MTDev
      run: sudo apt-get install -y mtdev-tools gettext
    
    # Set up Java 17 required by Gradle
    - name: Setup Java 17 required by Gradle
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'  # or 'zulu', 'liberica', etc.
        java-version: '17'

    - name: Build release
      run: |
        DATE=$(date +'%Y.%m.%d')
        xvfb-run poetry run python scripts/build.py --os android --version ${{ github.ref_name }} --automation

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: android-assets-${{ matrix.platform }}
        path: ${{ github.workspace }}/dist/carveracontroller-community-*.apk
        retention-days: 2

  publish-release:
    needs: [ build-windows-artifacts, build-macos-artifacts, build-linux-artifacts ]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Publish release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            windows-assets-*/carveracontroller-community-*-windows-x64.exe
            macos-assets-*/carveracontroller-community-*.dmg
            linux-assets-*/carveracontroller-community-*.appimage
            android-assets-*/carveracontroller-community-*.apk
